### ISSUE TITLE
Early release of tkey-fido

### ISSUE THREAD

**Issue by mchack-work** [tillitis/tkey-fido#2]
To make tkey-fido more palatable for testing, we:

- [ ] Maybe change application protocol. Currently we send, for instance, two responses to u2f_register. OK? Or do we change?
- [ ] Application state machine. Tidy up, make explicit.
- [ ] Add systemd unit
- [ ] man page
- [ ] Do an early release with goreleaser

**Comment by dehanj** [comment]
When testing the debugging-version of webauthn or other website, it seems as an authentication generates a registration event in the Tkey instead, and hence the authentication fails.

Also seems as we are hardcoding a counter of "1", should probably be "0".

**Comment by mchack-work** [comment]
We stopped working on tkey-fido to focus on Standalone FIDO2 project with some hardware changes, too.

The tkey-fido repo will probably be deleted.

Closing.
