### ISSUE TITLE
FIDO2 certification is planned or not ?

### ISSUE THREAD

**Issue by AkechiShiro** [tillitis/tkey-fido#6]
Hi,
I'm just wondering if it's planned because Microsoft requires this certification in order to accept to support FIDO2 authentification with for instance the tkey : https://learn.microsoft.com/en-us/entra/identity/authentication/concept-fido2-hardware-vendor

If that's something that is aimed at in the futur, I suppose.

**Comment by mchack-work** [comment]
We are in the process of investigating this. There are levels of certifications. Some of them are right out since we don't have the allowed hardware.

At least FIDO L1 should be possible, I think.
